# Copyright 2026 Zyvor AI Labs · https://zyvor.dev
# SPDX-License-Identifier: Apache-2.0

[workspace]
resolver = "3"
members = [
    "crates/fluxvm-core",
    "crates/fluxvm-cgroup",
    "crates/fluxvm-storage",
    "crates/fluxvm-network",
    "crates/fluxvm-image",
    "crates/fluxvm-guest-protocol",
    "crates/fluxvm-guest-agent",
    "crates/fluxvm-vsock-client",
    "crates/fluxvm-qemu",
    "crates/fluxvm-cloud-hypervisor",
    "crates/fluxvm-firecracker",
    "crates/fluxvm-hypervisor",
    "crates/fluxvm-scheduler",
    "crates/fluxvm-api",
    "crates/fluxvm-cli",
    "crates/fluxvm-agent",
    "crates/fluxvm-kube",
]
