# Copyright 2026 Zyvor AI Labs · https://zyvor.dev
# SPDX-License-Identifier: Apache-2.0

[package]
name = "fluxvm-cloud-hypervisor"
version = "0.3.0"
edition = "2024"
license = "Apache-2.0"
description = "Cloud Hypervisor VmBackend implementation for Zyvor FluxVM"

[dependencies]
fluxvm-core = { path = "../fluxvm-core" }
anyhow = "1"
async-trait = "0.1"
